import { Language } from 'react-highlight-syntax';

const handelLanguage = (language: string): Language => {
  switch (language.toLowerCase()) {
    case 'asp':
    case 'aspx':
      return 'Visual Basic .NET';
    case 'c':
      return 'C';
    case 'c++':
    case 'cpp':
    case 'cplusplus':
      return 'C++';
    case 'c#':
    case 'csharp':
      return 'C#';
    case 'clj':
    case 'cljc':
    case 'cljx':
    case 'clojure':
      return 'Clojure';
    case 'css':
      return 'CSS';
    case 'd':
      return 'D';
    case 'dart':
      return 'Dart';
    case 'diff':
    case 'patch':
      return 'Diff';
    case 'dockerfile':
    case 'docker':
      return 'Dockerfile';
    case 'erl':
    case 'erlang':
      return 'Erlang';
    case 'go':
      return 'Go';
    case 'gql':
    case 'graphql':
      return 'GraphQL';
    case 'gradle':
      return 'Gradle';
    case 'groovy':
      return 'Groovy';
    case 'handlebars':
    case 'hbs':
      return 'Handlebars';
    case 'haskell':
      return 'Haskell';
    case 'html':
    case 'xhtml':
    case 'xml':
      return 'HTML';
    case 'java':
      return 'Java';
    case 'js':
    case 'javascript':
    case 'jsx':
    case 'node':
      return 'JavaScript';
    case 'coffeescript':
    case 'coffee':
      return 'CoffeeScript';
    case 'json':
      return 'JSON';
    case 'julia':
    case 'jl':
      return 'Julia';
    case 'kotlin':
    case 'kt':
      return 'Kotlin';
    case 'less':
      return 'Less';
    case 'lua':
      return 'Lua';
    case 'makefile':
    case 'make':
      return 'Makefile';
    case 'markdown':
    case 'md':
      return 'Markdown';
    case 'objc':
    case 'objectivec':
    case 'objc++':
    case 'objcpp':
    case 'objectivecpp':
    case 'objectivec++':
    case 'objectivecplusplus':
      return 'Objective-C';
    case 'ocaml':
    case 'ml':
      return 'OCaml';
    case 'perl':
    case 'pl':
      return 'Perl';
    case 'php':
      return 'PHP';
    case 'powershell':
    case 'ps1':
      return 'PowerShell';
    case 'python':
    case 'py':
      return 'Python';
    case 'r':
      return 'R';
    case 'ruby':
    case 'rb':
      return 'Ruby';
    case 'rust':
    case 'rs':
      return 'Rust';
    case 'sass':
    case 'scss':
      return 'SCSS';
    case 'scala':
    case 'sc':
      return 'Scala';
    case 'shell':
    case 'sh':
    case 'zsh':
      return 'Bash';
    case 'cql':
    case 'mssql':
    case 'mysql':
    case 'plsql':
    case 'postgres':
    case 'postgresql':
    case 'pgsql':
    case 'sql':
    case 'sqlite':
      return 'SQL';
    case 'swift':
      return 'Swift';
    case 'ts':
    case 'typescript':
    case 'tsx':
      return 'TypeScript';
    case 'yaml':
    case 'yml':
      return 'YAML';
    default:
      return 'Plain text';
  }
};

export default handelLanguage;
